name: Image
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  register:
    name: Package, Publish, and Register
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - id: checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      env:
        VERSION: "${{ inputs.version }}"
        PACKAGE: "ghcr.io/gton-capital/stablecoins-liquidator"
        GITHUB_NPM_REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ env.PACKAGE }}:${{ env.VERSION }},${{ env.PACKAGE }}:latest
        build-args: GITHUB_NPM_REGISTRY_TOKEN=${GITHUB_NPM_REGISTRY_TOKEN}
